# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        # Python 3.8.5 is used on the server hosting the production bot
        python-version: 3.8.5
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install shared libraries
      run: |
        sudo apt-get install libpython3.8
    - name: Build Rust code
      run: |
        bash scripts/build.sh
    - name: Run test script
      run: |
        cp config-example.json config.json
        bash scripts/test.sh
#     - name: Upload Rust code coverage
#       uses: actions-rs/tarpaulin@v0.1
#       with:
#         args: --no-default-features
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
